name: Windows

on: [push, pull_request]

jobs:
  msbuild:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build Release
      shell: cmd
      run: msbuild Osiris.sln /p:Platform=x64 /p:Configuration=Release
    - name: Publish DLL as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: OsirisDll
        path: ./x64/Release/Osiris.dll
